name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build binary
        run: |
          go build -v -o gallery main.go

      - name: Run binary to generate templates (one-shot)
        run: |
          # Run the binary to allow it to create templates/index.html and static if needed.
          ./gallery &
          # give it a moment to create files
          sleep 2
          # stop the process
          pkill -f ./gallery || true

      - name: Prepare publish directory
        run: |
          mkdir -p public
          # Copy generated templates and static content to public
          if [ -d templates ]; then cp -r templates/* public/ || true; fi
          if [ -d static ]; then cp -r static public/static || true; fi
          # Ensure index.html exists at site root
          if [ -f templates/index.html ]; then cp templates/index.html public/index.html || true; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
